version: '3'

services:
  app:
    image: 'drone:0.0.1-SNAPSHOT'
    build:
      context: ./
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/drone
      - SPRING_DATASOURCE_USERNAME=drone
      - SPRING_DATASOURCE_PASSWORD=drone
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    tty: true
    stdin_open: true
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
  db:
    image: 'postgres:latest'
    container_name: db
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "drone" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=drone
      - POSTGRES_PASSWORD=drone
      - POSTGRES_DB=drone
      - APP_DB_USER=drone
      - APP_DB_PASS=drone
      - APP_DB_NAME=drone
    volumes:
      - ./init:/docker-entrypoint-initdb.d/